name = "CFTimeSchemes"
uuid = "79282218-dfaf-41aa-91df-a06f65ece871"
authors = ["The ClimFlows contributors"]
version = "0.3.3"

[deps]
MutatingOrNot = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[extensions]
Adapt_Ext = "Adapt"

[compat]
Adapt = "4"
MutatingOrNot = "0.1"
PackageExtensionCompat = "1"
julia = "1.8"

[extras]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
