name = "CFTimeSchemes"
uuid = "79282218-dfaf-41aa-91df-a06f65ece871"
authors = ["The ClimFlows contributors"]
version = "0.2.0"

[deps]
MutatingOrNot = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"

[compat]
julia = "1.8"
MutatingOrNot = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
